apiVersion: v2
name: grafana-stack
version: 1.0.0
dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.3.0"
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.2.0"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.2.0"
- name: "grafana"
  condition: grafana.enabled
  version: "~6.45.0"
  repository:  "https://grafana.github.io/helm-charts"
- name: "prometheus"
  condition: prometheus.enabled
  version: "~18.4.0"
  repository:  "https://prometheus-community.github.io/helm-charts"
- name: "filebeat"
  condition: filebeat.enabled
  version: "~7.8.0"
  repository:  "https://helm.elastic.co"
- name: "logstash"
  condition: logstash.enabled
  version: "~7.17.3"
  repository:  "https://helm.elastic.co"