---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: testcluster
  source:
    chart: loki-stack
    helm:
      values: |
        fluent-bit:
          enabled: true
        promtail:
          enabled: false
        grafana:
          enabled: true 
        prometheus:
          enabled: true 

          alertmanager:
            persistentVolume:
              enabled: false

          server:
            persistentVolume:
              enabled: false
      #valueFiles:
      #  - ./values.yaml
    repoURL: https://grafana.github.io/loki/charts
    #/index.yaml to check
    targetRevision: 2.1.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true