fluent-bit:
  enabled: true
promtail:
  enabled: false
filebeat:
  enabled: false
grafana:
  enabled: true 
  ingress: 
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: 
      - grafana.kube.gitma.de
    tls:
      - hosts:
        - grafana.kube.gitma.de
  grafana.ini:
    server:
      root_url: https://grafana.kube.gitma.de
    auth:
      oauth_auto_login: true
      disable_login_form: true
    auth.generic_oauth:
      enabled: true
      name: "hetzner-k8s"
      allow_sign_up: true
      client_id: "hetzner-k8s"
      scopes: "openid profile email"
      auth_url: https://kc.gitma.de/auth/realms/k8s/protocol/openid-connect/auth
      token_url: https://kc.gitma.de/auth/realms/k8s/protocol/openid-connect/token
      api_url: https://kc.gitma.de/auth/realms/k8s/protocol/openid-connect/userinfo
      role_attribute_path: contains(groups[*], '/admin') && 'Admin' || contains(groups[*], 'editor'  ) && 'Editor' || 'Viewer'
      team_ids_attribute_path: contains(groups[*], '/admin') && 'Admin' || contains(groups[*], 'editor'  ) && 'Editor' || 'Viewer'
  envFromSecret: oidc-login
  datasources: 
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://grafana-prometheus-server
        access: proxy
        isDefault: true
  dashboards: {}
    default:
      prometheus-stats:
        gnetId: 2
        revision: 2
        datasource: Prometheus
      node-exporter-full:
        gnetId: 1860
        datasource: Prometheus
        revision: 25

  #persistence:
  #  enabled: true
prometheus:
  enabled: true 

  alertmanager:
    persistentVolume:
      enabled: false

  server:
    persistentVolume:
      enabled: false