fluent-bit:
  enabled: true
promtail:
  enabled: false
filebeat:
  enabled: false
grafana:
  enabled: true 
  ingress: 
    enabled: true
    hosts: 
      - grafana.kube.gitma.de
    tls:
      - hosts:
        - grafana.kube.gitma.de
  #persistence:
  #  enabled: true
prometheus:
  enabled: true 

  alertmanager:
    persistentVolume:
      enabled: false

  server:
    persistentVolume:
      enabled: false