---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  #admin.enabled: "false"
  url: https://argocd.kube.gitma.de/
  oidc.config: |
    name: Keycloak
    issuer: https://kc.gitma.de/auth/realms/k8s
    clientID: hetzner-k8s
    clientSecret: $oidc.auth0.clientSecret
    requestedScopes: ["openid", "profile", "email"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, /admin, role:admin
