apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/cloud/deploy.yaml

patchesStrategicMerge:
  #- patch-deployment.yaml
  - patch-service.yaml

patchesJson6902:
- target:
    #version: v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
  patch: |-
    - op: replace
      path: "/kind"
      value: DaemonSet
